# Generated by Django 2.2.16 on 2020-11-12 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Board_Thread',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('open', 'open thread'), ('closed', 'closed thread')], default='open', max_length=10)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_name', to='restapi.Board')),
            ],
        ),
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('auth_token', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBoardMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('moderator', 'moderator User'), ('member', 'only member User'), ('banned', 'banned User')], default='moderator', max_length=10)),
                ('board', models.ManyToManyField(to='restapi.Board')),
                ('user', models.ManyToManyField(to='restapi.User_Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Thread_Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_name', to='restapi.User_Detail')),
                ('thread_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_comment', to='restapi.Board_Thread')),
            ],
        ),
        migrations.AddField(
            model_name='board_thread',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_creator', to='restapi.User_Detail'),
        ),
        migrations.AddField(
            model_name='board',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_creator', to='restapi.User_Detail'),
        ),
    ]
